### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by wwoofbum** [pietern/goestools#155]
Compiled & run successfully on Raspberry Pi 4B, under PiOS Buster (after failing to compile under Bullseye).  Moving SD card to a Pi 3B, all else the same, executing 'goesrecv -v -i 1 -c ~/goesrecv.conf ' responds with "Illegal instruction"

**Comment by DakotaNelson** [comment]
I'm having the same problem; only twist on my end is I didn't compile/install goesproc (`-DBUILD_GOESPROC=OFF`).

**Comment by DakotaNelson** [comment]
Looks like the same issue as #147

**Comment by DakotaNelson** [comment]
Ok, as for helpful details - I'm running on a Pi Zero:

```
pi@goesrcv:~/goestools $ uname -a
Linux goesrcv 5.15.61+ #1579 Fri Aug 26 11:08:59 BST 2022 armv6l GNU/Linux
```

It was installed using this ansible script, with `build_goesrecv` true.

```
- name: Install goestools
  hosts: all
  tasks:

  - name: Install dependencies
    become: yes
    ansible.builtin.package:
      name:
        - zlib1g-dev
        - git
        - librtlsdr-dev
        - cmake
        - gcc
        - g++
      state: present

  - name: Download goestools
    git:
      repo: https://github.com/pietern/goestools.git
      dest: /home/pi/goestools
      recursive: true

  - name: Set up build directory
    file:
      path: /home/pi/goestools/build
      state: directory

  - name: Run cmake for goestools
    command: >
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
      -DBUILD_GOESPROC={{build_goesproc | default(false) | ternary('ON', 'OFF')}}
      -DBUILD_GOESRECV={{build_goesrecv | default(false) | ternary('ON', 'OFF')}}
    args:
      chdir: /home/pi/goestools/build

  - name: Make goestools
    make:
      chdir: /home/pi/goestools/build

  - name: Make install goestools
    become: true
    make:
      chdir: /home/pi/goestools/build
      target: install
```

The config file is:

```
[demodulator]
## Use LRIT mode for GOES-15.
# mode = "lrit"
## Use HRIT mode for GOES-16 or later.
mode = "hrit"
source = "rtlsdr"

# The section below configures the sample source to use.
#
# You can leave them commented out to use the default values for the
# demodulator mode you choose ("lrit" or "hrit"). To use and configure
# any of them, uncomment the section below, and change the demodulator
# source field to match the source you want to use.
#

# [airspy]
# frequency = 1694100000
##
## By default, goesrecv will use the lowest sample rate available.
## This is 2.5 MSPS for the R2 and 3.0 MSPS for the Mini.
## Because different Airspy models support different sample rates,
## it is recommended to leave the "sample_rate" field commented,
## so that it works for either model.
##
# sample_rate = 3000000
# gain = 18
# bias_tee = false

[rtlsdr]
frequency = 1694100000
sample_rate = 2400000
gain = 30
bias_tee = false
device_index = 0

# [nanomsg]
# sample_rate = 2400000
# connect = "tcp://1.2.3.4:5005"
# receive_buffer = 2097152

[costas]
max_deviation = 200e3

[clock_recovery.sample_publisher]
bind = "tcp://0.0.0.0:5002"
send_buffer = 2097152

[quantization.soft_bit_publisher]
bind = "tcp://0.0.0.0:5001"
send_buffer = 1048576

[decoder.packet_publisher]
bind = "tcp://0.0.0.0:5004"
send_buffer = 1048576

# The demodulator stats publisher sends a JSON object that describes
# the state of the demodulator (gain, frequency correction, samples
# per symbol), for every block of samples.
#[demodulator.stats_publisher]
#bind = "tcp://0.0.0.0:6001"

# The decoder stats publisher sends a JSON object for every packet it
# decodes (Viterbi corrections, Reed-Solomon corrections, etc.).
#[decoder.stats_publisher]
#bind = "tcp://0.0.0.0:6002"

# The monitor can log aggregated stats (counters, gauges, and
# histograms) to a statsd daemon. Because this uses UDP, you can keep
# this enabled even if you haven't setup a statsd daemon yet.
#[monitor]
#statsd_address = "udp4://localhost:8125"
```
